// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_4k_club = "CgkIzOaKsp0HEAIQAw"; // <GPGSID>
        public const string achievement_6k_club = "CgkIzOaKsp0HEAIQBA"; // <GPGSID>
        public const string achievement_2k_club = "CgkIzOaKsp0HEAIQAg"; // <GPGSID>
        public const string achievement_miner = "CgkIzOaKsp0HEAIQCA"; // <GPGSID>
        public const string achievement_shopaholic = "CgkIzOaKsp0HEAIQBg"; // <GPGSID>
        public const string achievement_collector = "CgkIzOaKsp0HEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIzOaKsp0HEAIQAQ"; // <GPGSID>
        public const string achievement_marathon = "CgkIzOaKsp0HEAIQBw"; // <GPGSID>

}

